### ISSUE TITLE
Keyword amount

### ISSUE THREAD

**Issue by creatfive** [bmachek/lrc-ai-assistant#14]
Thanks a lot for this awesome free plugin! It’s really helpful. Is there any way to tweak the number of keyword results?

**Comment by bmachek** [comment]
I suppose you are using Gemini 1.5 flash, and on some pictures you're receiving a aweful lot of keywords? There's no other solution other than using Gemini Pro at the moment. It seems to be a bug in Gemini flash. I already tried adapting the phrase, which is ignored unfortunately.

**Comment by creatfive** [comment]
If we can control the amount number of keywords being generated, that would be awesome

**Comment by creatfive** [comment]
Oh I see, just let me know if those problems are fixed, I really like your work

**Comment by bmachek** [comment]
As mentioned I added support for Gemini 2.0 flash to the plugin. Could please go ahead and try if Gemini 2.0 still has this issue?

**Comment by bmachek** [comment]
So the issue, that for your liking there are too little keywords generated. Could you be specific which kind of descriptive keywords are missing?
