### ISSUE TITLE
Output is always in English, when keywords are turned off

### ISSUE THREAD

**Issue by bmachek** [bmachek/lrc-ai-assistant#2]
Another Thing i saw is that when i dont use tags the output is in english language and when using tags i get everything in system language, german. An other idea would be to be able to set the language of the output in the setings.

Reported by @xDrAcHeNx

**Comment by bmachek** [comment]
Release v1.2.0 should fix this.

**Comment by xDrAcHeNx** [comment]
Jep, works, Output is in System language
